credentials:
  users:
    rafa.parrra:
      name: Rafa Parrra
      password: "r94cd8jGq1g3"
    ARM:
      name: ARM
      password: "HOt5w0FzfMFf"
    Fabo:
      name: Fabo
      password: "J8laMITm1L3X"

cookie:
  name: quizapp_session
  key: alguna_clave_secreta_aleatoria
  expiry_days: 1
