credentials:
  usernames:
    <usuario1>:
      name: <Nombre 1>
      password: <Contraseña 1>
    <usuario2>:
      name: <Nombre 2>
      password: <Contraseña 2>
    …
cookie:
  name: quizapp_session
  key: alguna_clave_secreta_aleatoria
  expiry_days: 1
